(setq user-emacs-directory "~/.emacs.d")
(add-to-list 'load-path (concat user-emacs-directory "/mine"))

(package-initialize)
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("marmalade" . "http://marmalade-repo.org/packages/")
                         ("melpa" . "http://melpa.milkbox.net/packages/")
			 ("tromey" . "http://tromey.com/elpa/")))
(require 'scala-mode)
(require 'ensime)
(require 'magit)
(add-hook 'scala-mode-hook 'ensime-scala-mode-hook)
(global-set-key (kbd "C-c C-g") 'magit-status)
(require 'switch-window)
    (global-set-key "\C-xo" 'switch-window)
(server-start)
